# Default values for dc-app-01
# These values will be overridden by environment-specific values files

replicaCount: 1

image:
  repository: alpine
  tag: "3.19"  # This will be overridden by environment-specific tag
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 50m
    memory: 8Mi
  requests:
    cpu: 10m
    memory: 4Mi

command:
  - /bin/sh
  - -c
  - while true; do sleep 3600; done

service:
  type: ClusterIP
  port: 80 

# Environment-specific configurations (redis, kafka) have been moved to:
# - values-dev.yaml: Development environment configuration
# - values-qa.yaml: QA environment configuration 