# QA environment specific values for dc-app-01

# Redis connection configuration for QA
redis:
  host: "redis-qa.example.com"
  port: "6379"
  db: "1"
  useSsl: "true"
  username: "qa-user"
  # password will be provided by a Secret, not in ConfigMap

# Kafka connection configuration for QA
kafka:
  bootstrapServers: "kafka-qa-1.example.com:9092,kafka-qa-2.example.com:9092"
  clientId: "app-qa"
  securityProtocol: "SASL_SSL"
  autoOffsetReset: "latest"
  groupId: "consumers-qa" 